const { SlashCommandBuilder, ApplicationCommandType } = require('discord.js');

module.exports = [
    new SlashCommandBuilder().setName('вызвать').setDescription('Создать контракт'),
    new SlashCommandBuilder().setName('казна').setDescription('Показать баланс казны'),
    new SlashCommandBuilder().setName('пополнить').setDescription('Пополнить казну').addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('вычесть').setDescription('Списать из казны').addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('должники').setDescription('Список должников'),
    new SlashCommandBuilder().setName('долг_добавить').setDescription('Добавить должника').addStringOption(o => o.setName('ник').setDescription('Ник').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('оплачено').setDescription('Закрыть обычный долг').addStringOption(o => o.setName('ник').setDescription('Ник').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('оплачено_просрочка').setDescription('Закрыть долг из просрочки').addStringOption(o => o.setName('ник').setDescription('Ник').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('оплачено_крит').setDescription('Закрыть долг из критической просрочки').addStringOption(o => o.setName('ник').setDescription('Ник').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('чек_контракты').setDescription('Принудительно проверить все таймеры'),
    new SlashCommandBuilder().setName('статистика').setDescription('Показать актуальную статистику бота'),
    new SlashCommandBuilder().setName('контракт_список').setDescription('Список активных контрактов'),
    new SlashCommandBuilder().setName('ожидают').setDescription('Показать контракты, ожидающие оплаты'),
    new SlashCommandBuilder().setName('просрочка').setDescription('Начислить штраф за просрочку (сумма × 1.25) + дедлайн 48ч').addStringOption(o => o.setName('ник').setDescription('Ник должника').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма долга').setRequired(true)),
    new SlashCommandBuilder().setName('критическая').setDescription('Начислить штраф за критическую просрочку (сумма × 1.25) + дедлайн 48ч').addStringOption(o => o.setName('ник').setDescription('Ник должника').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма долга').setRequired(true)),
    new SlashCommandBuilder().setName('внести_оплату').setDescription('Внести оплату по контракту (вручную)').addStringOption(o => o.setName('название').setDescription('Название контракта').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма оплаты').setRequired(true)).addStringOption(o => o.setName('участники').setDescription('Ники участников через ;').setRequired(true)),
    new SlashCommandBuilder().setName('отметить_оплачено').setDescription('Отметить долг как оплаченный (ТОЛЬКО отметка, НЕ списывает из debtors)').addStringOption(o => o.setName('ник').setDescription('Ник должника').setRequired(true)).addStringOption(o => o.setName('контракт').setDescription('Название контракта').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма долга').setRequired(true)),
    new SlashCommandBuilder().setName('убрать_отметку').setDescription('Удалить отметку об оплате (на крайний случай)').addStringOption(o => o.setName('ник').setDescription('Ник должника').setRequired(true)).addStringOption(o => o.setName('контракт').setDescription('Название контракта').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('внести_в_кошелек').setDescription('Добавить деньги в кошелёк игрока').addStringOption(o => o.setName('ник').setDescription('Ник игрока').setRequired(true)).addIntegerOption(o => o.setName('сумма').setDescription('Сумма').setRequired(true)),
    new SlashCommandBuilder().setName('кошелек').setDescription('Показать баланс кошелька игрока').addStringOption(o => o.setName('ник').setDescription('Ник игрока').setRequired(true)),
    new SlashCommandBuilder().setName('оплатить_с_кошелька').setDescription('Оплатить с кошелька').addStringOption(o => o.setName('ник').setDescription('Ник игрока').setRequired(true)).addStringOption(o => o.setName('контракт').setDescription('Название контракта').setRequired(true)).addIntegerOption(o => o.setName('сумма_долга').setDescription('Сумма долга').setRequired(true)),
    new SlashCommandBuilder().setName('очистить_контракт').setDescription('Удалить все записи по названию контракта (админ)').addStringOption(o => o.setName('название').setDescription('Название контракта').setRequired(true)),
    new SlashCommandBuilder().setName('удалить_контракт').setDescription('Принудительно удалить контракт из БД (без редактирования сообщения)').addStringOption(o => o.setName('msgid').setDescription('ID сообщения с контрактом').setRequired(true)),
    { name: 'Импортировать контракт', type: ApplicationCommandType.Message },
    { name: 'Закрыть контракт', type: ApplicationCommandType.Message },
    { name: 'Напомнить о закрытии', type: ApplicationCommandType.Message },
    { name: 'Принудительно оплатить', type: ApplicationCommandType.Message },
    { name: 'Импортировать оплату', type: ApplicationCommandType.Message },
];